export default {
    background: "#333",
    primary: "#999",
    secondary: "#fff",
    success: "#fff",
    error: "#fff",
    errorLight: "#fff",
    warning: "#fff",
    title: "#fff",
    subtitle: "#fff",
    border: "#fff",
    black: "#fff",
    white: "#fff",
    placeholder: "#fff",
}